version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

  app:
    build: .
    ports:
      - "50051:50051"
    volumes:
      - ./:/app # Mounts a local application directory
      -  C:/Users/rralcala/remote-home/mflow-data:/app/mflow-data # Mounts a named volume
      -  C:/Users/rralcala/code/mflow/cache:/app/cache
volumes:
  mongodb-data: