# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/expense.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protobuf/expense.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf/expense.proto\x12\x0emflow.protobuf\"\xa2\x01\n\x07\x45xpense\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x12\n\naccount_id\x18\x07 \x01(\t\x12\x0c\n\x04tags\x18\x08 \x03(\t\x12\x12\n\ncreated_at\x18\t \x01(\x03\"@\n\x14\x43reateExpenseRequest\x12(\n\x07\x65xpense\x18\x01 \x01(\x0b\x32\x17.mflow.protobuf.Expense\"A\n\x15\x43reateExpenseResponse\x12(\n\x07\x65xpense\x18\x01 \x01(\x0b\x32\x17.mflow.protobuf.Expense2n\n\x0e\x45xpenseService\x12\\\n\rCreateExpense\x12$.mflow.protobuf.CreateExpenseRequest\x1a%.mflow.protobuf.CreateExpenseResponseBG\n\x1b\x63om.rralcala.mflow.protobufZ(github.com/rralc/mflow/protobuf;protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.expense_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.rralcala.mflow.protobufZ(github.com/rralc/mflow/protobuf;protobuf'
  _globals['_EXPENSE']._serialized_start=43
  _globals['_EXPENSE']._serialized_end=205
  _globals['_CREATEEXPENSEREQUEST']._serialized_start=207
  _globals['_CREATEEXPENSEREQUEST']._serialized_end=271
  _globals['_CREATEEXPENSERESPONSE']._serialized_start=273
  _globals['_CREATEEXPENSERESPONSE']._serialized_end=338
  _globals['_EXPENSESERVICE']._serialized_start=340
  _globals['_EXPENSESERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
