# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings


from exp_proto import expense_pb2 as protobuf_dot_expense__pb2

import grpc.experimental

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protobuf/expense_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExpenseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateExpense = channel.unary_unary(
                '/mflow.protobuf.ExpenseService/CreateExpense',
                request_serializer=protobuf_dot_expense__pb2.CreateExpenseRequest.SerializeToString,
                response_deserializer=protobuf_dot_expense__pb2.CreateExpenseResponse.FromString,
                _registered_method=True)


class ExpenseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateExpense(self, request, context):
        """Creates a new expense and returns the created record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExpenseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateExpense': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExpense,
                    request_deserializer=protobuf_dot_expense__pb2.CreateExpenseRequest.FromString,
                    response_serializer=protobuf_dot_expense__pb2.CreateExpenseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mflow.protobuf.ExpenseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mflow.protobuf.ExpenseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExpenseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateExpense(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mflow.protobuf.ExpenseService/CreateExpense',
            protobuf_dot_expense__pb2.CreateExpenseRequest.SerializeToString,
            protobuf_dot_expense__pb2.CreateExpenseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
