from abc import ABC, abstractmethod
from typing import Tuple
from datetime import datetime

class Asset(ABC):
    """
    Abstract base class for all asset classes.
    """

    @abstractmethod
    def get_income(self, today: datetime) -> Tuple[float, str]:
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_liquid_balance(self) -> Tuple[float, str]:
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_current_value(self) -> Tuple[float, str]:
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass
