from abc import ABC, abstractmethod
from datetime import date, datetime
from typing import Tuple


class Asset(ABC):
    """
    Abstract base class for all asset classes.
    """

    @abstractmethod
    def get_budgeted_income(self, year_month: datetime) -> Tuple[float, str]:
        """
        Method to get the budgeted income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_actual_income(
        self, year_month: datetime, include_capital=True
    ) -> Tuple[float, str]:
        """
        Method to get the actual income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    def get_income_balance(self, year_month: datetime) -> Tuple[float, str]:
        """
        Method to get the income balance of the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_market(self) -> str:
        """
        Method to get the market of the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_location(self) -> Tuple[str, str]:
        """
        Method to get the location of the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def calculate_year_performance(self) -> Tuple[float, float, str]:
        """ """
        pass

    @abstractmethod
    def get_timeline(self, end: datetime) -> list[Tuple[date, Tuple[float, str, bool]]]:
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_liquid_balance(self) -> Tuple[float, str]:
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_current_value(self) -> Tuple[float, str]:
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_currency(self) -> str:
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def get_returns(self) -> Tuple[float, float]:
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass

    @abstractmethod
    def is_liquid(self) -> bool:
        """
        Method to determine if the asset is liquid.
        Optional method, can be overridden by subclasses.
        """
        pass
