from abc import ABC, abstractmethod

class Asset(ABC):
    """
    Abstract base class for all asset classes.
    """

    @abstractmethod
    def get_total_value(self):
        """
        Method to get the current value of the asset.
        Must be implemented by subclasses.
        """
        pass

    @abstractmethod
    def get_current_value(self):
        """
        Method to get a description of the asset.
        Must be implemented by subclasses.
        """
        pass
    
    @abstractmethod
    def get_income(self):
        """
        Method to get the income generated by the asset.
        Optional method, can be overridden by subclasses.
        """
        pass