import logging
from datetime import date, datetime
from typing import Any, Dict, List, Tuple

from asset_classes.asset import Asset
from lib.config import DATE_FORMAT_STRING
from data.datasource import DataSource


class Bond(Asset):
    """Class representing a bond asset."""

    def __init__(
        self,
        identifier: str,
        capital: float,
        interest_rate: float,
        maturity_date: str,
        currency: str,
    ):
        self.identifier = identifier
        self.country = "PY"
        self.capital = capital
        self.currency = currency
        self.interest_rate = interest_rate
        if isinstance(maturity_date, datetime):
            self.maturity_date = maturity_date
        else:
            self.maturity_date = datetime.strptime(maturity_date, DATE_FORMAT_STRING)
        self.payment_schedule: List[Dict[str, Any]] = []

    def get_liquid_balance(self) -> Tuple[float, str]:
        return 0.0, self.currency

    def get_timeline(self, end: datetime) -> List[Tuple[date, Tuple[float, str]]]:
        timeline = []
        for payment in self.payment_schedule:
            payment_date = payment["date"]
            if payment_date <= end and payment["paid"] != 1:
                timeline.append(
                    (payment_date.date(), (payment["amount"], self.currency))
                )
        maturity_datetime = self.maturity_date
        if maturity_datetime <= end:
            timeline.append((maturity_datetime.date(), (self.capital, self.currency)))
        return timeline

    def get_returns(self) -> Tuple[float, float]:
        return self.capital, self.interest_rate

    def get_income(self, today: datetime) -> Tuple[float, str]:
        """
        Returns the income generated by the asset.
        This method can be overridden by subclasses if needed.
        """
        total = 0.0
        maturity_datetime = datetime.strptime(self.maturity_date, DATE_FORMAT_STRING)
        if (
            maturity_datetime.month == today.month
            and maturity_datetime.year == today.year
        ):
            total += self.capital
        for d in self.payment_schedule:
            payment_date = datetime.strptime(d["date"], "%m/%d/%Y")
            if payment_date.month == today.month and payment_date.year == today.year:
                logging.debug("Payment not paid: %s", d)
                total += d["amount"]

        return total, self.currency

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the current value of the bond.
        This method can be overridden by subclasses if needed.
        """
        return self.capital, self.currency

    def get_currency(self) -> str:
        return self.currency

    def __repr__(self):
        return (
            "Bond ID:"
            + self.identifier
            + ", Face Value:"
            + str(self.capital)
            + ", Interest Rate: "
            + str(self.interest_rate)
            + ", Maturity Date: "
            + self.maturity_date
        )


def parse_bond(data: Dict[str, Any], sheet: str) -> Bond:
    """
    Function to parse account data from the provided data.

    :param data: List of lists containing the account data.
    :return: List of dictionaries with account information.
    """
    try:
        new_bond = Bond(
            identifier=data["name"],
            currency=data["currency"],
            capital=float(str(data["capital"]).replace(",", "")),
            interest_rate=float(str(data["interest"]).replace("%", "")) / 100,
            maturity_date=data["maturity_date"],
        )
    except ValueError as e:
        logging.error(
            f"Error parsing bond data: {data["capital"]} or {data['interest']}"
        )
        raise e
    payment_data = sheet.get_table(data["payment_schedule"])
    new_bond.payment_schedule = []
    for row in payment_data:
        first = str(row[0]).lower()
        if first == "seq" or first == "none":
            continue
        if isinstance(row[1], str):
            pdate = datetime.strptime(row[1], DATE_FORMAT_STRING)
        else:
            pdate = row[1]
        try:
            payment = {
                "seq": first,
                "date": pdate,
                "amount": float(str(row[2]).replace(",", "")),
                "paid": int(row[3]),
            }
        except ValueError as e:
            logging.error(f"Error parsing bond payment data: {first} {row}")
            raise e
        logging.debug(f"Payment: %s", payment)
        new_bond.payment_schedule.append(payment)

    return new_bond


def fetch(sheet: DataSource) -> Bond:
    data = sheet.get_sheet_settings()
    if "itype" not in data or data["itype"].lower() != "bond":
        raise ValueError("The first cell of the Summary sheet must be 'Type' and the")

    bond = parse_bond(data, sheet)

    return bond
