import logging
from datetime import datetime, date
from typing import Any, Dict, List, Tuple

from asset_classes.asset import Asset
from data.gdrive import get_sheet_settings, get_table
from lib.config import DATE_FORMAT_STRING


class Bond(Asset):
    """Class representing a bond asset."""

    def __init__(
        self,
        identifier: str,
        capital: float,
        interest_rate: float,
        maturity_date: str,
        currency: str,
    ):
        self.identifier = identifier
        self.country = "PY"
        self.capital = capital
        self.currency = currency
        self.interest_rate = interest_rate
        self.maturity_date = maturity_date
        self.payment_schedule: List[Dict[str, Any]] = []

    def get_liquid_balance(self) -> Tuple[float, str]:
        return 0.0, self.currency

    def get_timeline(self, end: datetime) -> List[Tuple[date, Tuple[float, str]]]:
        timeline = []
        for payment in self.payment_schedule:
            payment_date = datetime.strptime(payment["date"], DATE_FORMAT_STRING)
            if payment_date <= end and payment["paid"] != "1":
                timeline.append((payment_date.date(), (payment["amount"], self.currency)))
        maturity_datetime = datetime.strptime(self.maturity_date, DATE_FORMAT_STRING)
        if maturity_datetime <= end:
            timeline.append((maturity_datetime.date(), (self.capital, self.currency)))
        return timeline

    def get_returns(self) -> Tuple[float, float]:
        return self.capital, self.interest_rate

    def get_income(self, today: datetime) -> Tuple[float, str]:
        """
        Returns the income generated by the asset.
        This method can be overridden by subclasses if needed.
        """
        total = 0.0
        maturity_datetime = datetime.strptime(self.maturity_date, DATE_FORMAT_STRING)
        if (
            maturity_datetime.month == today.month
            and maturity_datetime.year == today.year
        ):
            total += self.capital
        for d in self.payment_schedule:
            date = datetime.strptime(d["date"], "%m/%d/%Y")
            if date.month == today.month and date.year == today.year:
                logging.debug(f"Payment not paid: {d}")
                total += d["amount"]

        return total, self.currency

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the current value of the bond.
        This method can be overridden by subclasses if needed.
        """
        return self.capital, self.currency

    def get_currency(self) -> str:
        return self.currency

    def __repr__(self):
        return f"Bond ID: {self.identifier}, Face Value: {self.capital}, Interest Rate: {self.interest_rate}, Maturity Date: {self.maturity_date}"


def parse_bond(data: Dict[str, Any], sheet: str) -> Bond:
    """
    Function to parse account data from the provided data.

    :param data: List of lists containing the account data.
    :return: List of dictionaries with account information.
    """
    new_bond = Bond(
        identifier=data["name"],
        currency=data["currency"],
        capital=float(data["capital"].replace(",", "")),
        interest_rate=float(data["interest"].replace("%", "")) / 100,
        maturity_date=data["maturity_date"],
    )
    payment_data = get_table(sheet, data["payment_schedule"])
    new_bond.payment_schedule = []
    for row in payment_data[1:]:
        payment = {
            "seq": row[0],
            "date": row[1],
            "amount": float(row[2].replace(",", "")),
            "paid": row[3],
        }
        logging.debug(f"Payment: {payment}")
        new_bond.payment_schedule.append(payment)

    return new_bond


def fetch(sheet: str) -> Bond:
    data = get_sheet_settings(sheet)
    if "itype" not in data or data["itype"].lower() != "bond":
        raise ValueError("The first cell of the Summary sheet must be 'Type' and the")

    bond = parse_bond(data, sheet)

    return bond
