from datetime import date, datetime
from typing import Any, Dict, List, Tuple

from asset_classes.asset import Asset
from lib.config import Config


class Bond(Asset):
    """Class representing a bond asset."""

    def __init__(
        self,
        identifier: str,
        capital: float,
        interest_rate: float,
        maturity_date: datetime,
        currency: str,
        country: str,
        entity: str,
    ):
        self.identifier = identifier
        self.country = country
        self.entity = entity
        self.capital = capital
        self.currency = currency
        self.interest_rate = interest_rate
        self.maturity_date = maturity_date
        self.payment_schedule: List[Dict[str, Any]] = []
        self.purchase_price = capital

    def is_liquid(self) -> bool:
        return False

    def get_market(self) -> str:
        return self.currency

    def get_location(self):
        return self.country, self.entity

    def calculate_year_performance(self) -> Tuple[float, float, str]:
        return self.get_current_value()[0], self.interest_rate, self.currency

    def get_liquid_balance(self) -> Tuple[float, str]:
        return 0.0, self.currency

    def get_timeline(self, end: datetime) -> List[Tuple[date, Tuple[float, str, bool]]]:
        timeline = []
        for payment in self.payment_schedule:
            payment_date = payment["date"]
            if payment_date <= end and not payment["paid"]:
                timeline.append(
                    (payment_date.date(), (payment["amount"], self.currency, False))
                )
        maturity_datetime = self.maturity_date
        if maturity_datetime <= end:
            timeline.append(
                (maturity_datetime.date(), (self.capital, self.currency, True))
            )
        return timeline

    def get_returns(self) -> Tuple[float, float]:
        return self.capital, self.interest_rate

    def get_budgeted_income(self, year_month: datetime) -> Tuple[float, str]:
        total = 0.0
        for d in self.payment_schedule:
            payment_date = d["date"]
            if (
                payment_date.month == year_month.month
                and payment_date.year == year_month.year
            ):
                total += d["amount"]
        return total, self.currency

    def get_actual_income(
        self, year_month: datetime, include_capital=True
    ) -> Tuple[float, str]:
        """
        Returns the actual income generated by the asset.
        This method can be overridden by subclasses if needed.
        """
        total = 0.0

        if (
            self.maturity_date.month == year_month.month
            and self.maturity_date.year == year_month.year
            and include_capital
        ):
            total += self.capital
        for d in self.payment_schedule:
            payment_date = d["date"]
            if (
                payment_date.month == year_month.month
                and payment_date.year == year_month.year
                and d["paid"]
            ):
                total += d["amount"]

        return total, self.currency

    def get_income_balance(
        self, year_month: datetime, include_capital=True
    ) -> Tuple[float, str]:
        """
        Returns the income balance of the asset.
        This method can be overridden by subclasses if needed.
        """
        total = 0.0

        if (
            self.maturity_date.month == year_month.month
            and self.maturity_date.year == year_month.year
            and include_capital
        ):
            total += self.capital
        for d in self.payment_schedule:
            payment_date = d["date"]
            if (
                payment_date.month == year_month.month
                and payment_date.year == year_month.year
                and not d["paid"]
            ):
                total += d["amount"]

        return total, self.currency

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the current value of the bond.
        This method can be overridden by subclasses if needed.
        """
        return self.capital, self.currency

    def get_currency(self) -> str:
        return self.currency

    def __repr__(self):
        return (
            "Bond("
            + self.identifier
            + ", Face Value:"
            + f"{self.capital:,.0f} {self.currency}"
            + ", Interest Rate: "
            + f"{self.interest_rate:.2%}"
            + ", Maturity Date: "
            + self.maturity_date.strftime(Config.DATE_FORMAT_STRING)
            + ")"
        )
