import logging
from typing import List, Dict, Any


from g_tools import get_sheet_settings, get_table, USDPYG


class DepositCertificate:
    """Represents a financial asset with its attributes and methods to calculate its value."""

    def __init__(
        self,
        capital: float,
        rate: float,
        currency: str,
        maturity: str,
        country: str,
        itype: str,
        entity: str,
        interest_schedule: List[Dict[str, Any]],
    ):
        self.capital = capital
        self.currency = currency
        self.rate = rate
        self.maturity = maturity
        self.country = country
        self.type = itype
        self.entity = entity
        self.interest_schedule: List[Dict[str, Any]] = interest_schedule
    def get_total_value(self) -> float:
        """
        Returns the value of the asset in USD.
        """
        value = self.capital / USDPYG if self.currency == "PYG" else self.capital
        #logging.debug(f"{self.entity} = {value}")
        return  value
    def __repr__(self):
        return f"DepositCertificate(symbol={self.entity}, value={self.capital}, currency={self.currency})"
    def get_income(self):
        """
        Returns the income generated by the asset.
        This method can be overridden by subclasses if needed.
        """
        return 0.0


def fetch_cd(sheet: str) -> DepositCertificate:
    data = get_sheet_settings(sheet)

    if "itype" not in data or data["itype"] != "CD":
        raise ValueError("The first cell of the Summary sheet must be 'Type' and the")

    ac_data = get_table(sheet, data["interest_schecule"])
    interest: List[Dict[str, Any]] = []

    for row in ac_data[1:]:  # Skip header row
        interest.append(
            {
                "seq": row[0],
                "expiration": row[1],
                "amount": float(row[2].replace(",", "")),
                "currency": row[3],
            }
        )

    cd = DepositCertificate(
        capital=float(data["capital"].replace(",", "")),
        currency=data["currency"],
        rate=float(data["rate"].replace("%", "")) / 100,
        maturity=data["maturity"],
        country=data["country"],
        itype=data["itype"],
        entity=data["entity"],
        interest_schedule=interest,
    )
    return cd
