import logging
from datetime import date, datetime
from typing import List, Tuple

from asset_classes.asset import Asset
from data import internal
from data.datasource import DataSource
from lib.config import Config
from lib.util import cron_runs


class Instrument(Asset):
    """Represents a financial asset with its attributes and methods to calculate its value."""

    def __init__(
        self,
        location: str,
        symbol: str,
        price: float,
        factor: float,
        qty: float,
        estimated_dividend: float,
        rate: float,
        dividend: str,
        currency: str,
        acquisition_date: datetime,
        acquisition_price: float,
        liquid: bool,
    ):
        self.symbol = symbol
        self.identifier = f"{location}_{symbol}"
        self.price = price
        self.factor = factor
        self.qty = qty
        self.currency = currency
        self.location = location
        self.country = Config.LOCATION_COUNTRY[location]
        self.estimated_dividend = estimated_dividend
        self.rate = rate
        self.dividend = dividend
        self.acquisition_date = acquisition_date
        self.acquisition_price = acquisition_price
        self.liquid = liquid
        self.need_update = True

    def calculate_year_performance(self) -> Tuple[float, float, str]:
        value, currency = self.get_current_value()
        return value, self.rate, currency

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the value of the asset in USD.
        """
        if self.need_update and self.symbol == "CROUSD":
            self.price = internal.exchange_rate("CROUSD")
        elif self.need_update and self.symbol == "BTCUSD":
            self.price = internal.exchange_rate("BTCUSD")
        self.need_update = False
        return self.qty * self.price * self.factor, self.currency

    def get_income(self, today: datetime, include_capital=True) -> Tuple[float, str]:
        """
        Returns the income generated by the asset.
        #TODO Check here for the dividend calendar
        """
        amount = self.estimated_dividend * self.factor

        return amount, self.currency

    def get_liquid_balance(self) -> Tuple[float, str]:
        return (
            self.qty * self.price * self.factor if self.liquid else 0.0
        ), self.currency

    def get_timeline(self, end: datetime) -> List[Tuple[date, Tuple[float, str, bool]]]:
        timeline = []
        balance = self.get_liquid_balance()
        if balance[0] != 0.0:
            amount, currency = balance
            timeline.append((datetime.today().date(), (amount, currency, True)))
        if self.estimated_dividend != 0.0:
            for date in cron_runs(self.dividend, datetime.today(), end):
                timeline.append(
                    (date.date(), (self.estimated_dividend, self.currency, False))
                )
        return timeline

    def get_currency(self) -> str:
        return self.currency

    def get_returns(self) -> Tuple[float, float]:
        """
        Returns the current value and the annualized return of the asset.
        """
        holding_period_days = (datetime.now() - self.acquisition_date).days
        if holding_period_days > 365.25:
            holding_period_years = holding_period_days / 365.25
            annualized_return = (
                (self.price / self.acquisition_price) - 1
            ) / holding_period_years
        else:
            annualized_return = (self.price / self.acquisition_price) - 1
        return self.get_current_value()[0], annualized_return + self.rate

    def __repr__(self):
        return f"Asset(symbol={self.symbol}, value={self.get_current_value()[0]}, currency={self.currency}, location={self.location}, liquid={self.liquid})"


def get_total_value(assets: List[Instrument]) -> float:
    """
    Returns the total value of the portfolio.
    """
    total = 0.0
    for asset in assets:
        value, _ = asset.get_current_value()
        total += value
    return total


def fetch(sheet: DataSource) -> List[Instrument]:
    sheet_settings = sheet.get_sheet_settings()

    if "itype" not in sheet_settings or sheet_settings["itype"].lower() != "portfolio":
        raise ValueError("The first cell of the Summary sheet must be 'Type' and the")

    ac_data = sheet.get_table(sheet_settings["portfolio_sheet"])
    assets: List[Instrument] = parse_portfolio(ac_data)

    return assets


def parse_portfolio(data: List[List[str]]) -> List[Instrument]:
    """
    Function to parse account data from the provided data.

    :param data: List of lists containing the account data.
    :return: List of dictionaries with account information.
    """
    parsed_accounts: List[Instrument] = []
    for row in data[1:]:  # Skip header row
        asset = Instrument(
            location=row[0],
            symbol=row[1],
            price=float(row[2].replace(",", "")),
            factor=float(row[3].replace(",", "")),
            qty=float(row[4].replace(",", "")),
            dividend=row[6],
            estimated_dividend=float(row[8].replace(",", "")),
            rate=float(row[7].replace("%", "")) / 100,
            currency=row[9],
            acquisition_date=datetime.strptime(row[10], Config.DATE_FORMAT_STRING),
            acquisition_price=float(row[11].replace(",", "")),
            liquid=True if row[13] == "1" else False,
        )
        if len(row) < 11:
            continue  # Skip rows that do not have enough columns
        parsed_accounts.append(asset)

    return parsed_accounts
