import calendar
from datetime import date, datetime
from typing import Any, List, Tuple

from asset_classes.asset import Asset
from data.datasource import DataSource
from data.exchange_rates import ExchangeRates
from lib.util import count_cron_runs, cron_runs
from lib.config import Config

class Instrument(Asset):
    """Represents a financial asset with its attributes and methods to calculate its value."""

    def __init__(
        self,
        country: str,
        location: str,
        symbol: str,
        price: float,
        factor: float,
        qty: float,
        estimated_dividend: float,
        rate: float,
        dividend: str,
        currency: str,
        acquisition_date: datetime,
        acquisition_price: float,
        liquid: bool,
        capital_rate: float
    ):
        self.symbol = symbol
        self.identifier = f"{location}_{symbol}"
        self.price = price
        self.factor = factor
        self.qty = qty
        self.currency = currency
        self.location = location
        self.country = country
        self.estimated_dividend = estimated_dividend
        self.rate = rate
        self.dividend = dividend
        self.acquisition_date = acquisition_date
        self.acquisition_price = acquisition_price
        self.liquid = liquid
        self.capital_rate = capital_rate

    def is_liquid(self) -> bool:
        return self.liquid

    def get_market(self) -> str:
        if self.symbol in ["CROUSD", "BTCUSD", "SOL", "ETH", "SOLUSD", "ETHUSD"]:
            return "Crypto"
        if self.symbol in Config.TRADED_STOCKS:
            return "StockMarket"
        if self.symbol in ["USDC"]:
            return "USD"
        return self.symbol

    def get_location(self):
        return self.country, self.location.split("_")[0]

    def calculate_year_performance(self) -> Tuple[float, float, str]:
        value, currency = self.get_current_value()
        return value, self.get_returns()[1], currency

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the value of the asset in USD.
        """
        if self.symbol == "CROUSD":
            self.price = ExchangeRates.exchange_rate("CROUSD")
        elif self.symbol == "BTCUSD":
            self.price = ExchangeRates.exchange_rate("BTCUSD")

        return self.qty * self.price * self.factor, self.currency

    def get_income_balance(self, year_month: datetime) -> Tuple[float, str]:
        """
        Method to get the income balance of the asset.
        """
        return self.get_actual_income(year_month, include_capital=False)

    def get_budgeted_income(self, year_month: datetime) -> Tuple[float, str]:
        return self.get_actual_income(year_month, include_capital=False)

    def get_actual_income(
        self, year_month: datetime, include_capital=True
    ) -> Tuple[float, str]:
        """
        Returns the actual income generated by the asset.
        #TODO Check here for the dividend calendar

        """
        year = year_month.year
        month = year_month.month
        amount = 0.0
        for date in cron_runs(
            self.dividend,
            datetime(year, month, 1),
            datetime(year, month, calendar.monthrange(year, month)[1]),
        ):
            amount += self.estimated_dividend * self.factor

        return amount, self.currency

    def get_liquid_balance(self) -> Tuple[float, str]:
        return (
            self.qty * self.price * self.factor if self.liquid else 0.0
        ), self.currency

    def get_timeline(self, end: datetime) -> List[Tuple[date, Tuple[float, str, bool]]]:
        timeline = []
        balance = self.get_liquid_balance()
        if balance[0] != 0.0:
            amount, currency = balance
            timeline.append((datetime.today().date(), (amount, currency, True)))
        if self.estimated_dividend != 0.0:
            for date in cron_runs(self.dividend, datetime.today(), end):
                timeline.append(
                    (date.date(), (self.estimated_dividend, self.currency, False))
                )
        return timeline

    def get_currency(self) -> str:
        return self.currency

    def get_returns(self) -> Tuple[float, float]:
        """
        Returns the current value and the annualized return of the asset.
        """
        holding_period_days = (datetime.now() - self.acquisition_date).days
        if holding_period_days > 365.25:
            holding_period_years = holding_period_days / 365.25
            annualized_return = (
                (self.price / self.acquisition_price) - 1
            ) / holding_period_years
        else:
            if self.acquisition_price == 0:
                annualized_return = 0.0
            else:
                annualized_return = (self.price / self.acquisition_price) - 1

        return self.get_current_value()[0], annualized_return + self.rate

    def __repr__(self):
        return f"Instrument({self.identifier}, value={self.get_current_value()[0]:,.0f} {self.currency}, rate={(self.rate*100):,.2f}% location={self.location}, liquid={self.liquid})"


def get_total_value(assets: List[Instrument]) -> float:
    """
    Returns the total value of the portfolio.
    """
    total = 0.0
    for asset in assets:
        value, _ = asset.get_current_value()
        total += value
    return total


def fetch(sheet: DataSource) -> List[Instrument]:
    sheet_settings = sheet.get_sheet_settings()

    if "itype" not in sheet_settings or sheet_settings["itype"].lower() != "portfolio":
        raise ValueError("The first cell of the Summary sheet must be 'Type' and the")

    ac_data = sheet.get_table(sheet_settings["portfolio_sheet"])
    assets: List[Instrument] = parse_portfolio(ac_data)

    return assets


def parse_portfolio(data: List[List[Any]]) -> List[Instrument]:
    """
    Function to parse account data from the provided data.

    :param data: List of lists containing the account data.
    :return: List of dictionaries with account information.
    """
    parsed_accounts: List[Instrument] = []
    for row in data[1:]:  # Skip header row
        symbol = row[2]
        price = ExchangeRates.exchange_rate(symbol)

        rate = float(row[8])
        year = datetime.now().year
        qty = float(row[5])
        if row[7] == "N":
            payouts = 0
            estimated_dividend = 0.0
        else:
            payouts = count_cron_runs(
                row[7], datetime(year, 1, 1), datetime(year, 12, 31)
            )
            estimated_dividend = qty * price * rate / payouts
        raise Exception("Deprecated")
        asset = Instrument(
            country=row[0],
            location=row[1],
            symbol=symbol,
            price=price,
            factor=float(row[4]),
            qty=qty,
            dividend=row[7],
            rate=rate,
            estimated_dividend=estimated_dividend,
            currency=row[9],
            acquisition_date=row[10],
            acquisition_price=float(row[11]),
            liquid=True if row[12] == 1 else False,
        )
        if len(row) < 11:
            continue  # Skip rows that do not have enough columns
        parsed_accounts.append(asset)

    return parsed_accounts
