from typing import List, Tuple
from asset_classes.asset import Asset
from lib.gdrive import get_sheet_settings, get_table


class Instrument(Asset):
    """Represents a financial asset with its attributes and methods to calculate its value."""

    def __init__(
        self,
        location: str,
        symbol: str,
        price: float,
        factor: float,
        qty: float,
        estimated_dividend: float,
        rate: float,
        dividend: str,
        currency: str,
    ):
        self.symbol = symbol
        self.price = price
        self.factor = factor
        self.qty = qty
        self.currency = currency
        self.location = location
        self.estimated_dividend = estimated_dividend
        self.rate = rate
        self.dividend = dividend

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the value of the asset in USD.
        """
        return self.qty * self.price * self.factor, self.currency

    def get_income(self):
        """
        Returns the income generated by the asset.
        This method can be overridden by subclasses if needed.
        """
        return self.estimated_dividend / 12, self.currency

    def __repr__(self):
        return f"Asset(symbol={self.symbol}, value={self.get_current_value()[0]}, currency={self.currency}, location={self.location})"


def get_total_value(assets: List[Instrument]) -> float:
    """
    Returns the total value of the portfolio.
    """
    total = 0.0
    for asset in assets:
        total += asset.get_current_value()
    return total


def fetch_portfolio(sheet: str) -> List[Instrument]:
    sheet_settings = get_sheet_settings(sheet)

    if "itype" not in sheet_settings or sheet_settings["itype"].lower() != "portfolio":
        raise ValueError("The first cell of the Summary sheet must be 'Type' and the")

    ac_data = get_table(sheet, sheet_settings["portfolio_sheet"])
    assets: List[Instrument] = parse_portfolio(ac_data)

    return assets


def parse_portfolio(data: List[List[str]]) -> List[Instrument]:
    """
    Function to parse account data from the provided data.

    :param data: List of lists containing the account data.
    :return: List of dictionaries with account information.
    """
    parsed_accounts: List[Instrument] = []
    for row in data[1:]:  # Skip header row
        asset = Instrument(
            location=row[0],
            symbol=row[1],
            price=float(row[2].replace(",", "")),
            factor=float(row[3].replace(",", "")),
            qty=float(row[4].replace(",", "")),
            dividend=row[6],
            estimated_dividend=float(row[8].replace(",", "")),
            rate=float(row[7].replace("%", "")) / 100,
            currency=row[9],
        )
        if len(row) < 10:
            continue  # Skip rows that do not have enough columns
        parsed_accounts.append(asset)

    return parsed_accounts
