import calendar
from datetime import datetime
from typing import Any, Dict, Tuple

from asset_classes.asset import Asset
from data.gdrive import get_sheet_settings
from lib.util import count_cron_runs
from data.db import Transactions

FORMAT = "%m/%d/%Y"


class Recurrent(Asset):
    """Represents a recurrent financial flow with its attributes and methods to calculate its value."""

    def __init__(
        self,
        amount: float,
        country: str,
        currency: str,
        identifier: str,
        end: str,
        recurrence: str,
        start: str,
        flow_class: str,
    ):
        self.identifier = identifier
        self.amount = amount
        self.country = country
        self.currency = currency
        self.start_date = datetime.strptime(start, FORMAT)
        self.maturity_date = datetime.strptime(end, FORMAT)
        self.recurrence = recurrence
        self.flow_class = flow_class

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the total value of the recurrent flow.
        """
        if self.flow_class == "loan":
            paid_amount = (
                count_cron_runs(self.recurrence, self.start_date, self.maturity_date)
                * self.amount
            )
            return paid_amount, self.currency
        return 0.0, "USD"

    def get_returns(self) -> Tuple[float, float]:
        return self.get_current_value()[0], 0.0

    def __repr__(self):
        return f"Recurrent ID: {self.identifier}, Class: {self.flow_class}, Face Value: {self.amount}, Maturity Date: {self.maturity_date}"

    def get_liquid_balance(self) -> Tuple[float, str]:
        """
        Returns the liquid balance of the recurrent flow.
        This method can be overridden by subclasses if needed.
        """
        return 0.0, self.currency

    def get_income(self, today: datetime) -> Tuple[float, str]:
        """
        Returns the income generated by the asset.
        This should calculate wether it's an expense or a loan.
        """
        start = today.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        end = last_date_of_month(today)

        if start >= self.start_date and end <= self.maturity_date:

            cash_flow = count_cron_runs(self.recurrence, start, end) * self.amount
        else:
            cash_flow = 0.0
        t = Transactions()

        for v in t.get(self.identifier, today.year, today.month):
            cash_flow += v["amount"]

        return cash_flow, self.currency

    def get_currency(self) -> str:
        return self.currency


def last_date_of_month(today: datetime) -> datetime:
    last_day = calendar.monthrange(today.year, today.month)[1]
    return today.replace(day=last_day)


def parse_recurrent(data: Dict[str, Any]) -> Recurrent:
    """
    Function to parse account data from the provided data.

    :param data: List of lists containing the account data.
    :return: List of dictionaries with account information.
    """
    new_bond = Recurrent(
        identifier=data["identifier"],
        flow_class=data["flow_class"].lower(),
        amount=float(data["amount"].replace(",", "")),
        country=data["country"],
        currency=data["currency"],
        end=data["end"],
        recurrence=data["recurrence"],
        start=data["start"],
    )

    return new_bond


def fetch(sheet: str) -> Recurrent:
    data = get_sheet_settings(sheet)
    if "itype" not in data or data["itype"].lower() != "recurrent":
        raise ValueError("The first cell of the Summary sheet must be 'itype' and the")

    bond = parse_recurrent(data)

    return bond
