import calendar
from datetime import date, datetime
from typing import Any, Dict, List, Tuple

from asset_classes.asset import Asset
from data.datasource import DataSource
from lib.config import Config
from lib.util import count_cron_runs, cron_runs


class Recurrent(Asset):
    """Represents a recurrent financial flow with its attributes and methods to calculate its value."""

    def __init__(
        self,
        identifier: str,
        parent_asset_id: str,
        country: str,
        amount: float,
        currency: str,
        recurrence: str,
        start: str,
        end: str,
        flow_class: str,
        rate: float = 0.0,
    ):
        self.identifier = identifier
        self.amount = amount
        self.country = country
        self.currency = currency
        self.rate = rate
        if isinstance(start, datetime):
            self.start_date = start
        else:
            self.start_date = datetime.strptime(start, Config.DATE_FORMAT_STRING)
        if isinstance(end, datetime):
            self.maturity_date = end
        else:
            self.maturity_date = datetime.strptime(end, Config.DATE_FORMAT_STRING)
        self.recurrence = recurrence
        self.flow_class = flow_class
        self.parent_asset_id = parent_asset_id

    def calculate_year_performance(self):
        """I suspect that recurrents don't have performance, but let's see."""
        return self.get_current_value()[0], self.rate, self.currency

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the total value of the recurrent flow.
        """
        if self.flow_class == "loan":
            paid_amount = (
                count_cron_runs(self.recurrence, self.start_date, self.maturity_date)
                * self.amount
            )
            return paid_amount, self.currency
        return 0.0, self.currency

    def get_timeline(self, end: datetime) -> List[Tuple[date, Tuple[float, str, bool]]]:
        timeline = []

        for date in cron_runs(self.recurrence, datetime.today(), end):
            if date >= self.start_date:
                timeline.append((date.date(), (self.amount, self.currency, False)))
        return timeline

    def get_returns(self) -> Tuple[float, float]:
        return self.get_current_value()[0], 0.0

    def __repr__(self):
        return f"ID: {self.identifier} Country: {self.country}, Class: {self.flow_class}, Face Value: {self.amount} {self.currency}, Maturity Date: {self.maturity_date}"

    def get_liquid_balance(self) -> Tuple[float, str]:
        """
        Returns the liquid balance of the recurrent flow.
        This method can be overridden by subclasses if needed.
        """
        return 0.0, self.currency

    def get_income(self, today: datetime, include_capital=True) -> Tuple[float, str]:
        """
        Returns the income generated by the asset.
        This should calculate wether it's an expense or a loan.
        """
        start = today.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        rec_start = self.start_date.replace(
            day=1, hour=0, minute=0, second=0, microsecond=0
        )
        end = last_date_of_month(today)
        if start >= rec_start and end <= self.maturity_date:
            runs = count_cron_runs(self.recurrence, start, end)
            cash_flow = runs * self.amount
        else:
            cash_flow = 0.0

        return cash_flow, self.currency

    def get_currency(self) -> str:
        return self.currency


def last_date_of_month(today: datetime) -> datetime:
    last_day = calendar.monthrange(today.year, today.month)[1]
    return today.replace(day=last_day)


def parse_recurrent(data: Dict[str, Any]) -> Recurrent:
    """
    Function to parse account data from the provided data.

    :param data: List of lists containing the account data.
    :return: List of dictionaries with account information.
    """
    new_rec = Recurrent(
        identifier=data["identifier"],
        flow_class=data["flow_class"].lower(),
        amount=float(str(data["amount"]).replace(",", "")),
        country=data["country"],
        currency=data["currency"],
        end=data["end"],
        recurrence=data["recurrence"],
        start=data["start"],
        parent_asset_id=data.get("parent_asset", ""),
        rate=data.get("rate", 0.0),
    )

    return new_rec


def fetch(sheet: DataSource) -> Recurrent:
    data = sheet.get_sheet_settings()
    if "itype" not in data or data["itype"].lower() != "recurrent":
        raise ValueError("The first cell of the Summary sheet must be 'itype' and the")

    bond = parse_recurrent(data)

    return bond
