from typing import Dict, Any, Tuple

from lib.gdrive import get_sheet_settings
from lib.util import count_cron_runs
from asset_classes.asset import Asset

class Recurrent(Asset):
    """Represents a recurrent financial flow with its attributes and methods to calculate its value.
    """
    def __init__(
        self,
        amount: float,
        country: str,
        currency: str,
        identifier: str,
        end: str,
        recurrence: str,
        start: str,
        flow_class: str,
    ):
        self.identifier = identifier
        self.amount = amount
        self.country = country
        self.currency = currency
        self.maturity_date = end
        self.start_date = start
        self.recurrence = recurrence
        self.flow_class = flow_class

    def get_current_value(self) -> Tuple[float, str]:
        """
        Returns the total value of the recurrent flow.
        """
        if self.flow_class == "loan":
            # For loans, the current value is the amount minus the paid amount
            paid_amount = count_cron_runs(self.recurrence, self.start_date, self.maturity_date) * self.amount
            return paid_amount, self.currency
        return 0.0,"USD"

    def __repr__(self):
        return f"Recurrent ID: {self.identifier}, Class: {self.flow_class}, Face Value: {self.amount}, Maturity Date: {self.maturity_date}"
    
    def get_income(self) -> Tuple[float, str]:
        """
        Returns the income generated by the asset.
        This method can be overridden by subclasses if needed.
        """
        return (self.amount, self.currency)

def parse_recurrent(data: Dict[str, Any]) -> Recurrent:
    """
    Function to parse account data from the provided data.

    :param data: List of lists containing the account data.
    :return: List of dictionaries with account information.
    """
    new_bond = Recurrent(
        identifier=data["identifier"],
        flow_class=data["flow_class"].lower(),
        amount=float(data["amount"].replace(",", "")),
        country=data["country"],
        currency=data["currency"],
        end=data["end"],
        recurrence=data["recurrence"],
        start=data["start"],
    )

    return new_bond


def fetch_recurrent(sheet: str) -> Recurrent:
    data = get_sheet_settings(sheet)
    if "itype" not in data or data["itype"].lower() != "recurrent":
        raise ValueError("The first cell of the Summary sheet must be 'itype' and the")

    bond = parse_recurrent(data)

    return bond
