# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cash_flow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cash_flow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61sh_flow.proto\x12\x05mflow\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n\x17GenerateTimelineRequest\x12\'\n\x03\x65nd\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"U\n\x07Payment\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\"D\n\x0f\x43ountryTimeline\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12 \n\x08payments\x18\x02 \x03(\x0b\x32\x0e.mflow.Payment\"E\n\x18GenerateTimelineResponse\x12)\n\ttimelines\x18\x01 \x03(\x0b\x32\x16.mflow.CountryTimeline2f\n\x0f\x43\x61shFlowService\x12S\n\x10GenerateTimeline\x12\x1e.mflow.GenerateTimelineRequest\x1a\x1f.mflow.GenerateTimelineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cash_flow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATETIMELINEREQUEST']._serialized_start=59
  _globals['_GENERATETIMELINEREQUEST']._serialized_end=125
  _globals['_PAYMENT']._serialized_start=127
  _globals['_PAYMENT']._serialized_end=212
  _globals['_COUNTRYTIMELINE']._serialized_start=214
  _globals['_COUNTRYTIMELINE']._serialized_end=282
  _globals['_GENERATETIMELINERESPONSE']._serialized_start=284
  _globals['_GENERATETIMELINERESPONSE']._serialized_end=353
  _globals['_CASHFLOWSERVICE']._serialized_start=355
  _globals['_CASHFLOWSERVICE']._serialized_end=457
# @@protoc_insertion_point(module_scope)
