# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cash_flow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "cash_flow.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import \
    timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x63\x61sh_flow.proto\x12\x05mflow\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto"B\n\x17GenerateTimelineRequest\x12\'\n\x03\x65nd\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"U\n\x07Payment\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t"D\n\x0f\x43ountryTimeline\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12 \n\x08payments\x18\x02 \x03(\x0b\x32\x0e.mflow.Payment"E\n\x18GenerateTimelineResponse\x12)\n\ttimelines\x18\x01 \x03(\x0b\x32\x16.mflow.CountryTimeline"9\n\x11ListAssetsRequest\x12\x11\n\tprint_pos\x18\x01 \x01(\x08\x12\x11\n\tprint_neg\x18\x02 \x01(\x08"3\n\nAssetEntry\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x11\n\tformatted\x18\x02 \x01(\t"W\n\x13\x43urrencySummaryItem\x12\x10\n\x08\x63urrency\x18\x01 \x01(\t\x12\x16\n\x0epositive_value\x18\x02 \x01(\x01\x12\x16\n\x0enegative_value\x18\x03 \x01(\x01"V\n\x11ReturnHistoryItem\x12\x15\n\rcurrent_value\x18\x01 \x01(\x01\x12\x16\n\x0e\x63urrent_return\x18\x02 \x01(\x01\x12\x12\n\nidentifier\x18\x03 \x01(\t"\xc8\x01\n\x12ListAssetsResponse\x12\x34\n\x10\x63urrency_summary\x18\x01 \x03(\x0b\x32\x1a.mflow.CurrencySummaryItem\x12\x30\n\x0ereturn_history\x18\x02 \x03(\x0b\x32\x18.mflow.ReturnHistoryItem\x12$\n\tpositives\x18\x03 \x03(\x0b\x32\x11.mflow.AssetEntry\x12$\n\tnegatives\x18\x04 \x03(\x0b\x32\x11.mflow.AssetEntry"\x1f\n\x0c\x42oolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe4\x01\n\x0f\x43\x61shFlowService\x12S\n\x10GenerateTimeline\x12\x1e.mflow.GenerateTimelineRequest\x1a\x1f.mflow.GenerateTimelineResponse\x12\x41\n\nListAssets\x12\x18.mflow.ListAssetsRequest\x1a\x19.mflow.ListAssetsResponse\x12\x39\n\nClearCache\x12\x16.google.protobuf.Empty\x1a\x13.mflow.BoolResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "cash_flow_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GENERATETIMELINEREQUEST"]._serialized_start = 88
    _globals["_GENERATETIMELINEREQUEST"]._serialized_end = 154
    _globals["_PAYMENT"]._serialized_start = 156
    _globals["_PAYMENT"]._serialized_end = 241
    _globals["_COUNTRYTIMELINE"]._serialized_start = 243
    _globals["_COUNTRYTIMELINE"]._serialized_end = 311
    _globals["_GENERATETIMELINERESPONSE"]._serialized_start = 313
    _globals["_GENERATETIMELINERESPONSE"]._serialized_end = 382
    _globals["_LISTASSETSREQUEST"]._serialized_start = 384
    _globals["_LISTASSETSREQUEST"]._serialized_end = 441
    _globals["_ASSETENTRY"]._serialized_start = 443
    _globals["_ASSETENTRY"]._serialized_end = 494
    _globals["_CURRENCYSUMMARYITEM"]._serialized_start = 496
    _globals["_CURRENCYSUMMARYITEM"]._serialized_end = 583
    _globals["_RETURNHISTORYITEM"]._serialized_start = 585
    _globals["_RETURNHISTORYITEM"]._serialized_end = 671
    _globals["_LISTASSETSRESPONSE"]._serialized_start = 674
    _globals["_LISTASSETSRESPONSE"]._serialized_end = 874
    _globals["_BOOLRESPONSE"]._serialized_start = 876
    _globals["_BOOLRESPONSE"]._serialized_end = 907
    _globals["_CASHFLOWSERVICE"]._serialized_start = 910
    _globals["_CASHFLOWSERVICE"]._serialized_end = 1138
# @@protoc_insertion_point(module_scope)
