# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

import proto.cash_flow_pb2 as cash__flow__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in cash_flow_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CashFlowServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateTimeline = channel.unary_unary(
            "/mflow.CashFlowService/GenerateTimeline",
            request_serializer=cash__flow__pb2.GenerateTimelineRequest.SerializeToString,
            response_deserializer=cash__flow__pb2.GenerateTimelineResponse.FromString,
            _registered_method=True,
        )


class CashFlowServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateTimeline(self, request, context):
        """Produce upcoming payment timeline grouped by country/instrument"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CashFlowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenerateTimeline": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateTimeline,
            request_deserializer=cash__flow__pb2.GenerateTimelineRequest.FromString,
            response_serializer=cash__flow__pb2.GenerateTimelineResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mflow.CashFlowService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("mflow.CashFlowService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class CashFlowService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateTimeline(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mflow.CashFlowService/GenerateTimeline",
            cash__flow__pb2.GenerateTimelineRequest.SerializeToString,
            cash__flow__pb2.GenerateTimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
